name: Generate contribution snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "23 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate light and dark contribution snakes
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: tanutomar2005
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Publish images to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: false
